CREATE TABLE "LocalReadings" (
	"stationtype"	TEXT,
	"PASSKEY"	TEXT,
	"dateutc"	TEXT,
	"tempinf"	TEXT,
	"humidityin"	TEXT,
	"baromrelin"	TEXT,
	"baromabsin"	TEXT,
	"tempf"	TEXT,
	"humidity"	TEXT,
	"winddir"	TEXT,
	"windspeedmph"	TEXT,
	"windgustmph"	TEXT,
	"maxdailygust"	TEXT,
	"hourlyrainin"	TEXT,
	"eventrainin"	TEXT,
	"dailyrainin"	TEXT,
	"weeklyrainin"	TEXT,
	"monthlyrainin"	TEXT,
	"totalrainin"	TEXT,
	"solarradiation"	TEXT,
	"uv"	TEXT,
	"batt_co2"	TEXT
)